inputs:
  version: 
    description: 'terra-ci release version'
    default: 'v0.9.2'
  checksum:
    description: 'sha256 of release binary'
    default: '2897c9b755379e47d2658fb23c8f95eb93a21e77e82b8014c4e1461bd64f7dbe'
runs:
  using: "composite"
  steps: 
    - name: install terra-ci
      run: |
        wget -q "https://github.com/p0tr3c-terraform/terra-ci/releases/download/${{ inputs.version }}/terra-ci-linux-amd"
        echo -n "${{ inputs.checksum }}  terra-ci-linux-amd" | sha256sum --check --status
        mv ./terra-ci-linux-amd ./terra-ci && chmod +x ./terra-ci
      shell: bash
