name: Test - Offline
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**.md'
      - 'Makefile'
      - '.github/**'
jobs:
  TestValidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - run: make test_terratest_validate
  TestSnykConfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: make test_snyk
        env:
          SNYK_TOKEN: "${{ secrets.SNYK_AUTH_TOKEN }}"
