name: Test - Offline
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - **.md
jobs:
  TestOffline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.2'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: make test_offline
